[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
major_version = 17

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[auth]
enabled = true
site_url = "http://localhost:3000"

[functions.analyze-image]
verify_jwt = true

[realtime]
enabled = true

[functions.tcg-price-lookup]
enabled = true
verify_jwt = true
import_map = "./functions/tcg-price-lookup/deno.json"
entrypoint = "./functions/tcg-price-lookup/index.ts"

[functions.tcg-price-updater]
enabled = true
verify_jwt = true
import_map = "./functions/tcg-price-updater/deno.json"
entrypoint = "./functions/tcg-price-updater/index.ts"
